global using CaptainLogger;
global using CaptainLogger.Contracts.Options;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Microsoft.Web.WebView2.Core;
global using Microsoft.Web.WebView2.WinForms;
global using Sedge.Browser.Controls;
global using Sedge.Browser.CustomEventArgs;
global using Sedge.Browser.Forms;
global using Sedge.Browser.Helpers;
global using Sedge.Browser.Hooks;
global using Sedge.Browser.Options;
global using Sedge.Browser.Win32;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.IO;
global using System.Management;
global using System.Runtime.InteropServices;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using System.Windows.Forms;
global using static Sedge.Browser.Helpers.Globals;
global using static Sedge.Browser.Helpers.Styles;
global using static Sedge.Browser.Win32.Win32Globals;
global using Ctrl = System.Windows.Forms.Control;
global using FormTimer = System.Windows.Forms.Timer;
